import Image from "next/image";
import React from "react";

const TechStack = () => {
  return (
    <div className="grid grid-cols-2 md:grid-cols-5 p-4 gap-4">
      <Image
        src="/re.svg"
        height={40}
        width={40}
        alt="aws"
        className=" mx-auto"
      />
      <Image
        src="/js.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/tail.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />{" "}
      <Image
        src="/node.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/ts.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/mongo.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/aws.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/docker.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/java.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/postgresql.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/python.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/restapi.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/spring.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/stripe.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/three.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
      <Image
        src="/wha.svg"
        height={40}
        width={40}
        alt="aws"
        className="mx-auto"
      />
    </div>
  );
};

export default TechStack;
